version: '3.4'

services:
  postgres:
    image: postgres:12
    restart: always
    container_name: fish_postgres
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  server:
    build: server/
    restart: always
    container_name: fish_server
    working_dir: /var/www/server
    volumes:
      - ./server/:/var/www/server/
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
    command: python manage.py runserver ${SERVER_HOST}:${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - postgres